#!/bin/bash

# Path to asadmin
ASADMIN=/Applications/NetBeans/glassfish-4.1.1/glassfish/bin/asadmin

# Database connection variables
USER=todo
PASSWORD=todo
PORT=5432
DATABASE=todo
SERVER=localhost

# Connection pool variables
DATASOURCE_CLASSNAME=org.postgresql.ds.PGSimpleDataSource
DB_URL=jdbc\\:postgresql\\://localhost\\:$PORT/$DATABASE
DRIVER_CLASS=org.postgresql.Driver
POOL_NAME=TODO

# JDBC resource variable
RESOURCE=jdbc/TODO

# Auth realm variables
JAAS_CONTEXT=jdbcRealm
JNDI=jdbc/TODO
USER_TABLE=APPUSER
USER_NAME_COLUMN=EMAIL
PASSWORD_COLUMN=PASSWORD
GROUP_NAME_COLUMN=CATEGORY
DIGEST=none
ENC=none
REALM_NAME=JDBC_TODO

# Create JDBC connection pool
$ASADMIN create-jdbc-connection-pool \
        --datasourceclassname $DATASOURCE_CLASSNAME \
        --restype javax.sql.DataSource \
        --property URL=$DB_URL:driverClass=$DRIVER_CLASS:Password=$PASSWORD:portNumber=$PORT:databaseName=$DATABASE:User=$USER:serverName=$SERVER $POOL_NAME

# Create JDBC resource
$ASADMIN create-jdbc-resource --connectionpoolid $POOL_NAME $RESOURCE

# Enable default principal to role mapping
$ASADMIN set server-config.security-service.activate-default-principal-to-role-mapping=true

# Create JDBC Realm
$ASADMIN create-auth-realm --classname com.sun.enterprise.security.auth.realm.jdbc.JDBCRealm \
  --property jaas-context=$JAAS_CONTEXT:datasource-jndi=$JNDI:user-table=$USER_TABLE:user-name-column=$USER_NAME_COLUMN:password-column=$PASSWORD_COLUMN:group-table=$USER_TABLE:group-name-column=$GROUP_NAME_COLUMN:digest-algorithm=$DIGEST:digestrealm-password-enc-algorithm=$ENC $REALM_NAME

# Set JDBC Realm as default
$ASADMIN set server-config.security-service.default-realm=$REALM_NAME




